### ISSUE TITLE
The description is always "no description given"

### ISSUE THREAD

**Issue by daniagudelos** [tbordovsky/gradle-debian-plugin#1]
Hi! 

The description of the package is always "no description given" regardless the configuration. You can see it also in the example of the repository.:

- In the build.gradle the configuration includes:

`description = 'A single line synopsis'`

- The file hello.changes has the line:

```
Description:
 hello-world - no description given
```

- The control file within the .deb file includes:

Description: no description given

**Comment by tbordovsky** [comment]
Thank you! I'll check it out.

**Comment by tbordovsky** [comment]
I just gave the wrong parameter name in the instructions, my apologies. I'll update the readme and the example with the correct one.

FFR, the correct configuration should read as follows: `packageDescription = 'A single line synopsis'`

**Comment by tbordovsky** [comment]
https://github.com/tbordovsky/gradle-debian-plugin/pull/2
